version: '3'
services:
 backend:
  build: ./backend
  ports:
   - "6060:6060"
  volumes:
   - ./backend:/usr/src/app
  environment:
   - ENV=development
   - PORT=6060
   - DB=mongodb+srv://akshat1701:SEDemo1234@cluster0.udjlpg8.mongodb.net/?retryWrites=true&w=majority
   #- DB=mongodb://mongodb:27017/todoDev
   

 frontend:
  build: .
  volumes:
    - ./src:/usr/src/app/src
    - ./public:/usr/src/app/public
    - ./test:/usr/src/app/test
  ports:
    - "3000:3000"
  stdin_open: true


networks:
 default:
  name: feature_hunt
